services:
  ros2:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: f1gym_ros2

    network_mode: host

    stdin_open: true
    tty: true

    volumes:
      - ../ros2_ws:/workspace/ros2_ws

    working_dir: /workspace