bridge:
  ros__parameters:

    # ==========================================================
    # Simulator
    # ==========================================================

    map_path: "/sim_ws/src/my_f1tenth_bridge/assets/maps/levine"
    map_ext: ".png"

    initial_x: 0.0
    initial_y: 0.0
    initial_theta: 0.0

    scan_rate_hz: 10.0

    # ==========================================================
    # Topics
    # ==========================================================

    scan_topic: "/scan"
    odom_topic: "/odom"
    drive_topic: "/drive"

    # ==========================================================
    # Frames
    # ==========================================================

    frame_id: "laser"
    odom_frame: "odom"
    base_frame: "base_link"

    # ==========================================================
    # Laser
    # ==========================================================

    scan_angle_min: -2.35
    scan_angle_max: 2.35

    range_min: 0.0
    range_max: 30.0
